test

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -9,15 +9,27 @@ jobs:
     steps:
       - name: Check out source repository
         uses: actions/checkout@v3
+
       - name: Set up Python environment
         uses: actions/setup-python@v4
         with:
-          python-version: "3.11"
-      - name: flake8 Lint
-        uses: py-actions/flake8@v2
-        with:
-          ignore: "F401"
-          exclude: "src/ignoreme.py"
-          max-line-length: "100"
-          path: "src"
-          plugins: "flake8-bugbear==22.1.11 flake8-black"
+          python-version: "3.10"
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8
+
+      - name: Run Flake8
+        run: |
+          flake8
+
+      - name: Check Flake8 results
+        run: |
+          flake8_result=$?
+          if [ $flake8_result -ne 0 ]; then
+            echo "Flake8 found errors. Commit will be cancelled."
+            exit 1
+          else
+            echo "No Flake8 errors found. Commit will proceed."
+          fi
